### ISSUE TITLE
Compile fail

### ISSUE THREAD

**Issue by arblake** [flagxor/eforth#1]
Brad,
I get an immediate compile failure:
arduino.template:1:1: error: expected unqualified-id before '{' token
 {{opcodes}}
 ^

**Comment by arblake** [comment]
Now I have this error when trying  make:
make: *** No rule to make target 'arduino/arduino.template.ino', needed by 'out/arduino/ueforth/ueforth.ino'.  Stop.

**Comment by arblake** [comment]
Compiled ok
When I try to start the wifi I get this :
--> wifi.begin
Guru Meditation Error: Core  1 panic'ed (LoadProhibited). Exception was unhandled.

**Comment by flagxor** [comment]
Wifi.begin requires some parameters, see:
https://eforth.appspot.com/

z" SSID" z" PASSWORD" WiFi.begin

Unfortunately, I have not yet found a good way to add runtime memory guards. ESP-32 doesn't have a real mmu, so anything will have a runtime cost.
