### ISSUE TITLE
Forth does not start

### ISSUE THREAD

**Issue by arblake** [flagxor/eforth#2]
Code compiles, loads but no "ok". This stopped after the addition of camera support. Booting begins:
rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0018,len:4
load:0x3fff001c,len:1044
load:0x40078000,len:8896
load:0x40080400,len:5816
entry 0x400806ac
.......
But a continuing full points across the screen

**Comment by flagxor** [comment]
I'm assuming this is stale, please reopen if not.
